CREATE TABLE IF NOT EXISTS uploads (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	title VARCHAR(256) NOT NULL,
	public_id VARCHAR(32) NOT NULL,
	owner VARCHAR(128) NOT NULL,
	uploaded DATETIME NOT NULL
);
