CREATE TABLE IF NOT EXISTS session (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	upload_id INTEGER NOT NULL,
	public_id VARCHAR(16) NOT NULL,
	started DATETIME NOT NULL,
	ended DATETIME,
	FOREIGN KEY (upload_id) REFERENCES uploads(id) ON DELETE CASCADE
);
