CREATE TABLE IF NOT EXISTS commands (
	id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	session_id INTEGER NOT NULL,
	cmd VARCHAR(32) NOT NULL,
	page INTEGER NOT NULL,
	timestamp DATETIME NOT NULL,
	FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
);
