ALTER TABLE commands MODIFY coordinates TEXT NOT NULL DEFAULT '';
ALTER TABLE commands MODIFY color VARCHAR(7) NOT NULL DEFAULT '';
ALTER TABLE commands MODIFY width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE commands MODIFY canvas_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE commands MODIFY canvas_height INTEGER NOT NULL DEFAULT 0;
